### ISSUE TITLE
Could this project apply to n point deformation in gimp ?

### ISSUE THREAD

**Issue by erhuodaosi** [siyliepfl/deformation-aware-unpaired-image-translation#2]
Wonderful work!

I'm sorry to bother you,but I have a question on could this project apply to n point deformation in gimp ?
I would very appreciate if you could help me,thank you!

**Comment by hrhodin** [comment]
I am not quite sure how you want to use it in gimp?
The method could for sure be extended to work with different deformation models; it is not particular to the one used.

**Comment by erhuodaosi** [comment]
Hi,

Thank you for your timely reply!Thanks a lot!

It's my fault that I could not explain it clearly,please forgive my poor English.I mean that if given some random control points by user in GUI,could we use this project to do random deformations by dragging the points like gimp?I notice that the project could be extended to work with different deformation models,could you give me some advice on how to do the deformation by your project?

I would very appreciate if you could help me,thank you! 
Thank you for your patient again.

Best,
FengLang

**Comment by siyliepfl** [comment]
Hi Fenglang,

Thanks. The deformation filed is a pixel-wised vector field learned by adversarial training which means it doesn't have any key-points. If you want to manually drag the keypoints in GUI, you may want to use some interpolation methods such as TPS.  

Best,
Siyuan
